name: Run build
on: [push, workflow_dispatch]
permissions: {}  # Set permissions at the job level

jobs:
  build:  # job name
    if: github.repository == 'mzdaniel/wheel'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Install build dependencies
      run:  pip install rust-just

    - name: Run build
      run:  just build

    - name: Publish GitHub Release
      env:
        VERSION: 0.0.1
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "$VERSION" -F build/notes.md build/g*.whl
